# Generated by Django 3.2.5 on 2021-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
